- name: Install desktop
  hosts: desktop

  vars_files:
    - passphrase.yml

  tasks:
    - name: Get passphrase
      shell: echo $PASSPHRASE
      environment:
        PASSPHRASE: "{{ passphrase }}"
      register: get_passphrase

    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa) and encrypted private key
      community.crypto.openssh_keypair:
        path: $HOME/.ssh/id_rsa_test
        passphrase: "{{ get_passphrase.stdout }}"
      register: perm_public_key

    - name: Report perm public_key
      ansible.builtin.debug:
        msg: "permanent public key is {{ perm_public_key.public_key }}"

    - import_tasks: ../common/install_as_nico.yml

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: $HOME/{{ item }}
        state: directory
      with_items:
        - software
        - data
        - datasets
        - tests
        - output
        - Learning
        - .ssh

    # Get the repos (submodule are automatically fetched)
    - name: git clone {{ item }}
      ansible.builtin.git:
        repo: git@bitbucket.org:slamcore/{{ item }}.git
        dest: /home/nico/software/{{ item }}
        accept_hostkey: true
        key_file: $HOME/.ssh/id_rsa_nop
      with_items:
        - acceptance_tests
        - slam_utils
        - online_poc
        - buildbot
      ignore_errors: true

    - name: git clone {{ item }}
      ansible.builtin.git:
        repo: git@github.com:slamcore/{{ item }}.git
        dest: /home/nico/software/{{ item }}
        accept_hostkey: true
        key_file: $HOME/.ssh/id_rsa_nop
      with_items:
        - position
        - slamtor
        - trajectory_evaluator
        - slamcore_packager
      ignore_errors: true

    - name: Pause until you have removed the keys in github and bitbucket
      ansible.builtin.pause:
