- name: Ensure the .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Generate an SSH key pair
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    size: 2048
    type: rsa
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0600"
    passphrase: "{{ ssh_key_passphrase }}" # Use encrypted passphrase
  register: ssh_key

- name: Display the generated public key
  ansible.builtin.debug:
    msg: "SSH public key is: {{ ssh_key.public_key }}"

- name: Git clone liquidprompt
  ansible.builtin.git: # noqa: latest
    repo: https://github.com/liquidprompt/liquidprompt.git
    dest: ~/liquidprompt
  ignore_errors: true

- name: Ensure the ~/.tmux/plugins/tpm directory exists
  ansible.builtin.file:
    path: "~/.tmux/plugins/tpm"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Git clone tmux plugins
  ansible.builtin.git: # noqa: latest
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
  ignore_errors: true

# - name: Install and load chezmoi
#   ansible.builtin.shell:
#     cmd: if ! which chezmoi; then sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply git@gitlab.com:nicolas.paquet.pro/chezmoi.git; fi
