- name: Install jetson
  hosts: jetson

  vars_files:
    - passphrase.yml

  tasks:
    - name: Import tasks
      ansible.builtin.import_tasks: ../common/install_as_nico.yml

    - name: Pause until you have removed the keys in github and bitbucket
      ansible.builtin.pause:
