- name: Clean matching webui-upgrade folders in buildbot home
  hosts: buildbots
  gather_facts: false
  tasks:
    # Using become_user to ensure the operation is performed as 'buildbot'
    - name: Find matching webui-upgrade folders
      ansible.builtin.find:
        paths: /home/buildbot/
        patterns: "buildbot/worker*/webui-upgrade*"
        file_type: directory
      register: found_dirs
      become: true
      become_user: buildbot

    # Removing directories as 'buildbot' user to avoid permission issues
    - name: Remove found webui-upgrade directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ found_dirs.files }}"
      become: true
      become_user: buildbot
      when: found_dirs.matched > 0
