- name: Create a file with some content
  hosts: buildbots
  become: true
  become_user: buildbot

  tasks:
    - name: Creating a file with content
      copy:
        dest: "/home/buildbot/.at_bisect_token"
        content: |
          <token>
