- name: Ansible get storage left on home
  hosts: buildbots

  tasks:
    - name: Get storage left
      ansible.builtin.shell: df -h|egrep 'Size|home'
      register: df

    - name: Printing results
      ansible.builtin.debug:
        msg: "{{ df.stdout_lines }}"
