- name: Ansible create user functionality module
  hosts: bb_2_6_7

  become: true
  tasks:
  - name: Create sudo nikos with a password and a home
    ansible.builtin.user:
      name: nikos
      comment: create user
      group: sudo
      password: '$6$krhuGXSQkTundEMm$ugAFY9.KTKFTVL62o.fmke2ChSp92pudWts/sB/E.kjNesveHvT9X8xTrQdADg7HMKceE6MBOlDPBI71rIqXQ0' # https://computingforgeeks.com/generate-linux-user-encrypted-password-for-ansible ("changemeplease")
      createhome: true
      home: /home/nikos
      shell: /bin/bash
      state: present
      append: true
  # TODO: user could be set with with_items?