- name: Ansible remove user
  hosts: buildbots

  become: yes
  tasks:
  - name: Remove <user>
    ansible.builtin.user:
      name: <user>
      comment: remove <user>
      state: absent
      remove: yes
